name: "LeetCode Synchronizer"

description: "Synchronize LeetCode submissions to GitHub."

branding:
  icon: git-commit
  color: blue

inputs:

  GITHUB_TOKEN:
    required: true
    description: GitHub Token

  LEETCODE_SESSION:
    required: true
    description: LeetCode Session Cookie

  LEETCODE_CSRF_TOKEN:
    required: true
    description: LeetCode CSRF Token

runs:

  using: composite

  steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run Synchronizer
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        LEETCODE_SESSION: ${{ inputs.LEETCODE_SESSION }}
        LEETCODE_CSRF_TOKEN: ${{ inputs.LEETCODE_CSRF_TOKEN }}
      run: |
        python ${{ github.action_path }}/main.py